[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_LOCALES = '["en", "es", "fr", "de", "pt-BR", "hi", "ru", "ko", "vi", "en-CA", "es-MX"]'
  NEXT_PUBLIC_DEFAULT_LOCALE = "en-GB"
  NEXTAUTH_DEMO_MODE = "true"
  NEXTAUTH_URL = "https://example.com"
  NEXTAUTH_SECRET = "your-next-auth-secret-key-change-in-production"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
